### ISSUE TITLE
mithril/jsx-uses-mithril unavailable

### ISSUE THREAD

**Issue by Michael-1** [dhinesh03/eslint-plugin-mithril#1]
The [link in the docs](https://github.com/dhinesh03/eslint-plugin-mithril/blob/master/docs/rules/jsx-uses-mithril.md) point to a 404, and there seems to be no rule **`mithril/jsx-uses-mithril`** available.

**Comment by dhinesh03** [comment]
It was my backlog list forget to removed. Now i've removed it.

**Comment by Michael-1** [comment]
Thanks for updating the documentation. However, I would find the rule quite useful.

I have the line `import m from "mithril"` in every UI component, must as I’m using JSX, `m` never show`s up in the code, having ESLint complaining. I’m currently setting `// eslint-disable-next-line no-unused-vars` in every file, as a workaround. But it would be convenient – and cleaner – to have a central rule to make it clear to ESLint that `m` is used implicitly by JSX.

Do you consider re-adding the rule? (I offer to create a pull request.)

**Comment by dhinesh03** [comment]
You are welcome to create a pull request. 
For a temporary solution  you can use the following code
 `new webpack.ProvidePlugin({
            m: 'mithril' //Global access
        }),` 
on your webpack plugin configuration. It will enable the m as global access without importing it.
